In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [67]:
df=pd.read_csv('Churn_Modelling.csv')

In [68]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [69]:
df.drop(columns=['RowNumber', 'CustomerId','Surname'], inplace=True)

In [63]:
#puting it latter for geting pkl

from sklearn.preprocessing import LabelEncoder
import pickle

gender_encoder = LabelEncoder()

df["Gender"] = gender_encoder.fit_transform(df["Gender"])

with open("gender_encoder.pkl", "wb") as f:
    pickle.dump(gender_encoder, f)

In [70]:
df.Gender=df['Gender'].map({'Female':0,'Male':1})

In [64]:
## i added it latter for geting encoding of one hot encoder for geography column

from sklearn.preprocessing import OneHotEncoder
import pickle

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

encoded = encoder.fit_transform(df[['Geography']])

with open('encoder.pkl', 'wb') as f:
    pickle.dump(encoder, f)

In [72]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1,0,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0,1,0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1,0,0

In [71]:
df = pd.get_dummies(df, columns=['Geography'], dtype=int)

In [73]:
import pickle

In [9]:
with open("feature_columns.pkl", "wb") as file:
    pickle.dump(df.columns.tolist(), file)

In [74]:
X = df.drop('Exited', axis=1)
y = df['Exited']

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y      # Recommended for classification
)

In [76]:
from sklearn.preprocessing import StandardScaler

num_cols = ['CreditScore', 'Age', 'Balance', 'Tenure', 'NumOfProducts', 'EstimatedSalary']

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [77]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

In [81]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
2151,1.058568,1,1.715086,0.684723,-1.226059,-0.910256,1,0,1.042084,1,0,0
8392,0.913626,1,-0.659935,-0.696202,0.413288,-0.910256,1,0,-0.623556,0,1,0
5006,1.079274,0,-0.184931,-1.731895,0.601687,0.808830,1,1,0.308128,0,1,0
4117,-0.929207,1,-0.184931,-0.005739,-1.226059,0.808830,1,0,-0.290199,1,0,0
7182,0.427035,1,0.955079,0.339492,0.548318,0.808830,0,1,0.135042,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4555,0.385623,0,-0.374933,0.339492,-1.226059,-0.910256,1,0,-1.294966,0,0,1
4644,0.634095,1,3.330101,-0.005739,-1.226059,0.808830,0,0,0.901685,0,0,1
8942,0.168210,0,-0.184931,1.375185,-0.073747,0.808830,1,1,-0.558088,1,0,0
2935,0.375270,1,-0.374933,1.029954,0.394991,0.808830,1,0,-1.351500,0,0,1
6206,1.565865,1,1.145081,0.684723,-1.226059,-0.910256,0,1,-1.026922,0,0,1

## ANN implementation

In [82]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [83]:
## build ann model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #hl1
    Dense(32, activation='relu'),#hl2
    Dense(1, activation='sigmoid')#output layer
])

c:\Users\ankit\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [84]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [85]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)

In [86]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['recall'])

In [87]:
## set up tensorboard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [88]:
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [89]:
# setup early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=100, restore_best_weights=True)
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [90]:
# train the model
history =model.fit(
    X_train,
    y_train,validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorflow_callback]


)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4392 - recall: 0.1454 - val_loss: 0.3928 - val_recall: 0.2850
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3707 - recall: 0.3828 - val_loss: 0.3577 - val_recall: 0.3391
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3524 - recall: 0.4337 - val_loss: 0.3425 - val_recall: 0.4840
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3439 - recall: 0.4632 - val_loss: 0.3403 - val_recall: 0.4840
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3395 - recall: 0.4669 - val_loss: 0.3457 - val_recall: 0.4324
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3357 - recall: 0.4656 - val_loss: 0.3373 - val_recall: 0.4889
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3326 - recall: 0.4742 - val_loss: 0.3378 - val_recall: 0.4717
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3312 - recall: 0.4785 - val_loss: 0.3382 - val_recall: 0.3931
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3282 - recall: 0.4736 - val_loss: 0.3436 - val_recall: 0.5307
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3269 - recall: 0.4742 - val_loss: 0.3359 - val_recall: 0.4717
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3250 - recall: 0.4828 - val_loss: 0.3426 - val_recall: 0.5430
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3249 - recall: 0.4859 - val_loss: 0.3393 - val_recall: 0.4668
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3213 - recall: 0.4969 - val_loss: 0.3384 - val_recall: 0.5209
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3200 - recall: 0.4969 - val_loss: 0.3390 - val_recall: 0.5307
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3185 - recall: 0.4975 - val_loss: 0.3376 - val_recall: 0.4816
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3164 - recall: 0.4914 - val_loss: 0.3374 - val_recall: 0.5381
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3165 - recall: 0.4957 - val_loss: 0.3357 - val_recall: 0.4742
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3151 - recall: 0.5006 - val_loss: 0.3419 - val_recall: 0.5086
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3144 - recall: 0.5025 - val_loss: 0.3388 - val_recall: 0.4373
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3133 - recall: 0.4963 - val_loss: 0.3368 - val_recall: 0.5258
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3114 - recall: 0.5098 - val_loss: 0.3383 - val_recall: 0.4963
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3109 - recall: 0.5043 - val_loss: 0.3398 - val_recall: 0.4963
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3104 - recall: 0.5080 - val_loss: 0.3462 - val_recall: 0.4521
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3082 - recall: 0.5000 - val_loss: 0.3487 - val_recall: 0.4423
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3080 - recall: 0.5061 - val_loss: 0.3446 - val_recall: 0.4988
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3056 - recall: 0.5190 - val_loss: 0.3619 - val_recall: 0.3931
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3061 - recall: 0.5233 - val_loss: 0.3476 - val_recall: 0.4644
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3048 - recall: 0.5209 - val_loss: 0.3471 - val_recall: 0.5381
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3041 - recall: 0.5215 - val_loss: 0.3461 - val_recall: 0.4988
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3034 - recall: 0.5252 - val_loss: 0.3445 - val_recall: 0.5111
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3023 - recall: 0.5331 - val_loss: 0.3433 - val_recall: 0.4545
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3024 - recall: 0.5252 - val_loss: 0.3459 - val_recall: 0.4496
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3003 - recall: 0.5221 - val_loss: 0.3455 - val_recall: 0.5184
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2987 - recall: 0.5209 - val_loss: 0.3473 - val_recall: 0.5381
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2988 - recall: 0.5319 - val_loss: 0.3461 - val_recall: 0.5356
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2963 - recall: 0.5301 - val_loss: 0.3515 - val_recall: 0.4619
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2960 - recall: 0.5362 - val_loss: 0.3487 - val_recall: 0.4570
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2952 - recall: 0.5411 - val_loss: 0.3487 - val_recall: 0.4693
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2939 - recall: 0.5454 - val_loss: 0.3527 - val_recall: 0.4423
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2942 - recall: 0.5399 - val_loss: 0.3460 - val_recall: 0.5061
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2915 - recall: 0.5429 - val_loss: 0.3547 - val_recall: 0.4054
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2917 - recall: 0.5423 - val_loss: 0.3514 - val_recall: 0.5430
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2918 - recall: 0.5509 - val_loss: 0.3485 - val_recall: 0.4545
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2897 - recall: 0.5466 - val_loss: 0.3621 - val_recall: 0.5332
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2897 - recall: 0.5521 - val_loss: 0.3537 - val_recall: 0.4939
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2877 - recall: 0.5521 - val_loss: 0.3597 - val_recall: 0.4398
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2874 - recall: 0.5503 - val_loss: 0.3540 - val_recall: 0.4349
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2850 - recall: 0.5571 - val_loss: 0.3594 - val_recall: 0.4300
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2856 - recall: 0.5583 - val_loss: 0.3654 - val_recall: 0.4373
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2845 - recall: 0.5601 - val_loss: 0.3537 - val_recall: 0.5332
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2850 - recall: 0.5571 - val_loss: 0.3569 - val_recall: 0.4988
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2831 - recall: 0.5577 - val_loss: 0.3598 - val_recall: 0.4717
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2827 - recall: 0.5632 - val_loss: 0.3609 - val_recall: 0.4668
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2813 - recall: 0.5564 - val_loss: 0.3575 - val_recall: 0.5086
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2806 - recall: 0.5589 - val_loss: 0.3647 - val_recall: 0.4103
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2803 - recall: 0.5687 - val_loss: 0.3524 - val_recall: 0.5111
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2805 - recall: 0.5748 - val_loss: 0.3611 - val_recall: 0.4595
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2783 - recall: 0.5650 - val_loss: 0.3741 - val_recall: 0.5971
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2799 - recall: 0.5791 - val_loss: 0.3606 - val_recall: 0.4644
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2789 - recall: 0.5681 - val_loss: 0.3596 - val_recall: 0.4963
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2774 - recall: 0.5779 - val_loss: 0.3619 - val_recall: 0.4840
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2770 - recall: 0.5742 - val_loss: 0.3647 - val_recall: 0.5061
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2767 - recall: 0.5724 - val_loss: 0.3675 - val_recall: 0.4226
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2749 - recall: 0.5748 - val_loss: 0.3770 - val_recall: 0.5651
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2744 - recall: 0.5816 - val_loss: 0.3688 - val_recall: 0.4545
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2736 - recall: 0.5822 - val_loss: 0.3718 - val_recall: 0.5209
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2744 - recall: 0.5859 - val_loss: 0.3677 - val_recall: 0.5381
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2728 - recall: 0.5908 - val_loss: 0.3652 - val_recall: 0.4939
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2721 - recall: 0.5834 - val_loss: 0.3686 - val_recall: 0.5135
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2732 - recall: 0.5761 - val_loss: 0.3746 - val_recall: 0.4545
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2707 - recall: 0.5908 - val_loss: 0.3668 - val_recall: 0.4865
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2706 - recall: 0.5779 - val_loss: 0.3718 - val_recall: 0.5184
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2696 - recall: 0.5865 - val_loss: 0.3702 - val_recall: 0.5037
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2701 - recall: 0.5939 - val_loss: 0.3757 - val_recall: 0.4201
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2699 - recall: 0.5933 - val_loss: 0.3724 - val_recall: 0.4963
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2689 - recall: 0.5957 - val_loss: 0.3707 - val_recall: 0.4840
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2665 - recall: 0.6061 - val_loss: 0.3697 - val_recall: 0.5430
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2673 - recall: 0.6000 - val_loss: 0.3696 - val_recall: 0.4668
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2685 - recall: 0.5877 - val_loss: 0.3767 - val_recall: 0.4644
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2664 - recall: 0.5926 - val_loss: 0.3806 - val_recall: 0.4767
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2663 - recall: 0.5865 - val_loss: 0.3805 - val_recall: 0.4521
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2658 - recall: 0.6000 - val_loss: 0.3740 - val_recall: 0.4595
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2656 - recall: 0.5926 - val_loss: 0.3765 - val_recall: 0.5233
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2651 - recall: 0.6006 - val_loss: 0.3809 - val_recall: 0.4963
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2650 - recall: 0.6025 - val_loss: 0.3766 - val_recall: 0.4742
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2616 - recall: 0.5994 - val_loss: 0.3828 - val_recall: 0.5111
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2614 - recall: 0.6006 - val_loss: 0.3746 - val_recall: 0.4963
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2619 - recall: 0.6037 - val_loss: 0.3861 - val_recall: 0.4398
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2625 - recall: 0.6037 - val_loss: 0.3780 - val_recall: 0.5233
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2624 - recall: 0.6049 - val_loss: 0.3841 - val_recall: 0.4324
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2611 - recall: 0.5994 - val_loss: 0.3832 - val_recall: 0.4889
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2598 - recall: 0.5994 - val_loss: 0.3955 - val_recall: 0.5553
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2600 - recall: 0.6110 - val_loss: 0.3855 - val_recall: 0.5528
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2591 - recall: 0.6104 - val_loss: 0.3787 - val_recall: 0.5012
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2581 - recall: 0.6110 - val_loss: 0.3745 - val_recall: 0.4889
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2580 - recall: 0.6104 - val_loss: 0.3897 - val_recall: 0.4816
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2570 - recall: 0.6202 - val_loss: 0.3863 - val_recall: 0.5258
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2566 - recall: 0.6086 - val_loss: 0.3891 - val_recall: 0.5405
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2568 - recall: 0.6233 - val_loss: 0.3854 - val_recall: 0.5012
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2551 - recall: 0.6184 - val_loss: 0.3916 - val_recall: 0.5479

In [91]:
model.save('model3.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [47]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [48]:
# load tensor board extenstion
%load_ext tensorboard

In [50]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 25432), started 0:01:16 ago. (Use '!kill 25432' to kill it.)